CREATE TABLE "PUBLIC"."员工基本信息"(
 "STAFFID" CHAR (8) NOT NULL ,
 "NAME" VARCHAR (10) NOT NULL ,
 "BIRTHDAY" DATE,
 "BIRTHPLACE" VARCHAR (50),
 "NATION" VARCHAR (50),
 "IDENTIFICATION" CHAR (18) NOT NULL ,
 "POLITICAL" VARCHAR (50),
 "DEPARTMENTID" VARCHAR (50) NOT NULL ,
 "ENTERDATE" DATE NOT NULL ,
 "DUTYID" CHAR (4) NOT NULL ,
 "TITLE" VARCHAR (50),
 "GRADUATIONSCHOOL" VARCHAR (50),
 "GRADUATIONDATE" DATE,
 "DEGREE" VARCHAR (50),
 "MAJOR" VARCHAR (50),
 "ADDRESS" VARCHAR (50),
 "CONTACTWAY" VARCHAR (50),
 "POSITIONSTATUS" CHAR (4),
 PRIMARY KEY ("STAFFID") USING INDEX TABLESPACE "SYSTEM",
 CONSTRAINT "员工基本信息_DEPARTMENTID_FKEY" FOREIGN KEY ("DEPARTMENTID") REFERENCES "PUBLIC"."部门信息" ("DEPARTMENTID") ON DELETE NO ACTION ON UPDATE NO ACTION NOT  DEFERRABLE ,
 CONSTRAINT "员工基本信息_DUTYID_FKEY" FOREIGN KEY ("DUTYID") REFERENCES "PUBLIC"."职务信息" ("DUTYID") ON DELETE NO ACTION ON UPDATE NO ACTION NOT  DEFERRABLE ) WITHOUT OIDS 
TABLESPACE "SYSTEM";

CREATE TABLE "PUBLIC"."工资标准"(
 "WAGESCALEID" CHAR (4) NOT NULL ,
 "WAGESCALENAME" VARCHAR (50) NOT NULL ,
 "BASICSALARY" REAL NOT NULL ,
 "SUBSIDY" REAL,
 "BONUS" REAL,
 "CARSUBSIDY" REAL,
 "MEDICALINSURANCE" REAL,
 "HOUSEPROVIDENTFUND" REAL,
 "HOUSESUBSIDY" REAL,
 "PENSION" REAL,
 PRIMARY KEY ("WAGESCALEID") USING INDEX TABLESPACE "SYSTEM") WITHOUT OIDS 
TABLESPACE "SYSTEM";


CREATE TABLE "PUBLIC"."工资计发信息"(
 "STAFFID" CHAR (8) NOT NULL ,
 "WAGESCALEID" CHAR (4) NOT NULL ,
 "BASICSALARY" REAL NOT NULL ,
 "SUBSIDY" REAL,
 "BONUS" REAL,
 "CARSUBSIDY" REAL,
 "HOUSESUBSIDY" REAL,
 "DEINSPECTION" REAL,
 "OVERTIMEPAY" REAL,
 "DEPENSION" REAL,
 "DEMEDICALINSURANCE" REAL,
 "DEHOUSEPTFUND" REAL,
 "TAXBEFTOTAL" REAL NOT NULL ,
 "INCOMETAX" REAL NOT NULL ,
 "REALWAGE" REAL NOT NULL ,
 "ACCOUNTDATE" DATE NOT NULL ,
 PRIMARY KEY ("STAFFID") USING INDEX TABLESPACE "SYSTEM") WITHOUT OIDS 
TABLESPACE "SYSTEM";

CREATE TABLE "PUBLIC"."考勤信息"(
 "STAFFID" CHAR (8) NOT NULL ,
 "ATTENDANCEDATE" DATE NOT NULL ,
 "ATTENDANCETYPE" VARCHAR (50) NOT NULL ,
 "DAYS" INTEGER NOT NULL ,
 "REMARK" TEXT NOT NULL ,
 PRIMARY KEY ("STAFFID") USING INDEX TABLESPACE "SYSTEM") WITHOUT OIDS 
TABLESPACE "SYSTEM";

CREATE TABLE "PUBLIC"."职务信息"(
 "DUTYID" CHAR (4) NOT NULL ,
 "DUTYNAME" VARCHAR (50) NOT NULL ,
 "WAGESCALEID" CHAR (4) NOT NULL ,
 "INTRODUCTION" TEXT,
 PRIMARY KEY ("DUTYID") USING INDEX TABLESPACE "SYSTEM") WITHOUT OIDS 
TABLESPACE "SYSTEM";

CREATE TABLE "PUBLIC"."部门信息"(
 "DEPARTMENTID" CHAR (4) NOT NULL ,
 "DEPARTMENTNAME" VARCHAR (50) NOT NULL ,
 "LEADERNAME" CHAR (10) NOT NULL ,
 "ADDRESS" VARCHAR (50),
 "TELPHONE" VARCHAR (50),
 "INTRODUCTION" TEXT NOT NULL ,
 PRIMARY KEY ("DEPARTMENTID") USING INDEX TABLESPACE "SYSTEM") WITHOUT OIDS 
TABLESPACE "SYSTEM";


